//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absensi
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Kelas { get; set; }
        public Nullable<int> SetAbsen { get; set; }
        public Nullable<System.DateTime> Tanggal { get; set; }
        public Nullable<System.TimeSpan> Waktu { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Kantin Kantin { get; set; }
    }
}
