//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CanteenEntities2 : DbContext
    {
        public DB_CanteenEntities2()
            : base("name=DB_CanteenEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absensi> Absensis { get; set; }
        public virtual DbSet<Kantin> Kantins { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Penjualan> Penjualans { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
