//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string NamaMenu { get; set; }
        public Nullable<decimal> HPP { get; set; }
        public Nullable<decimal> Harga { get; set; }
        public Nullable<int> SetId { get; set; }
        public int Stock { get; set; }
        public string NamaSupplier { get; set; }
    
        public virtual Kantin Kantin { get; set; }
    }
}
