//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penjualan
    {
        public int Id { get; set; }
        public string NamaMenu { get; set; }
        public int StockAkhir { get; set; }
        public int SetId { get; set; }
        public decimal Keuntungan { get; set; }
        public Nullable<System.DateTime> TanggalPenjualan { get; set; }
    
        public virtual Kantin Kantin { get; set; }
    }
}
